### ISSUE TITLE
Output suggestion: add a new line after AssertionFailedException

### ISSUE THREAD

**Issue by akhansari** [d-edge/Diffract#14]
It might be visually easier to compare the expected and actual output like this:

To reproduce
```fsharp
Diffract.Assert(true, false)
```
Actual
```
Diffract.AssertionFailedException: Expect = true
Actual = false
```
Expected
```
Diffract.AssertionFailedException
Expect = true
Actual = false
```

But not when there is a text after
```
Diffract.AssertionFailedException: ResultValue collection differs:
  ResultValue[0].Item.Amount Expect = 101M
                             Actual = 10M
```

The goal would be to have a alignement between Expect and Actual.

**Comment by Tarmil** [comment]
Good point! I think it would make sense to implement this for `Assert`, and leave `ToString` and `Write` as is, since this is an issue that only really happens due to the way exceptions are printed.

Or maybe this could be an option in `PrintParams`; this way `Assert` would defaut it to `true` and the others to `false`.
